---
certbot_auto_renew: true
certbot_admin_email: admin@example.com

# Certbot auto-renew cron job configuration (for certificate renewals).
certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
certbot_auto_renew_hour: 3
certbot_auto_renew_minute: 30
certbot_auto_renew_options: "--quiet --renew-hook 'service nginx reload' > /dev/null 2>&1"

# Parameters used when creating new Certbot certs.
certbot_create_if_missing: true
certbot_create_method: standalone
certbot_certs: []
# - email: janedoe@example.com
#   domains:
#     - example1.com
#     - example2.com
# - domains:
#     - example3.com
#certbot_create_command: >-
#  {{ certbot_script }} certonly --standalone --noninteractive --agree-tos
#  --email {{ cert_item.email | default(certbot_admin_email) }}
#  -d {{ cert_item.domains | join(',') }}
certbot_create_command: >-
    {{ certbot_script }} --agree-tos --register-unsafely-without-email
    --staple-ocsp --webroot certonly -w /opt/letsencrypt
    -d {{ ansible_fqdn}} -d  www.{{ ansible_fqdn }}
    creates=/etc/letsencrypt/live/{{ ansible_fqdn }}/chain.pem"

certbot_create_standalone_stop_services:
  - nginx
  # - apache
  # - varnish

# To install from source (on older OSes or if you need a specific or newer
# version of Certbot), set this variable to `yes` and configure other options.
certbot_install_from_source: false
certbot_repo: https://github.com/certbot/certbot.git
certbot_version: master
certbot_keep_updated: true

