---
# Firewalld setup
- name: Firewalld service state
  service: name=firewalld state=started enabled=yes

- name: insert firewalld rule for nginx
  firewalld:
   service: http
   zone: public
   permanent: true
   state: enabled

- name: insert firewalld rule for nginx
  firewalld:
   service: https
   zone: public
   permanent: true
   state: enabled

- name: insert firewalld rule for nginx
  firewalld:
   service: ssh
   zone: public
   permanent: true
   state: enabled

- name: Firewalld service state
  service: name=firewalld state=reloaded enabled=yes
