---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-FreeBSD.yml
  when: ansible_os_family == 'FreeBSD'

- include_tasks: setup-OpenBSD.yml
  when: ansible_os_family == 'OpenBSD'

- include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

# Vhost configuration.
#- import_tasks: vhosts.yml

# Firealld setup.
- name: Setup configs dirs
  include: dirs.yml

- name: Setup common config
  include: common_config.yml

- name: Setup ssl config
  include: ssl.yml

- name: Setup umi config
  include: umi_config.yml
  when: "'umi-cms' in group_names"

# Firealld setup.
- name: Setup firewalld
  include: firewalld.yml

- name: Ensure nginx is started and enabled to start at boot.
  service: name=nginx state=started enabled=yes
