---
- name: Ensure nginx is installed.
  openbsd_pkg:
    name: "{{ nginx_package_name }}"
    state: present
  register: nginx_package_name
  until: nginx_package_name is succeeded

- name: Create logs directory.
  file:
    path: /var/log/nginx
    state: directory
