---
# PyOpenSSl > 0.15
- name: Generate self-signed SSL certificates
  command:
    cmd: openssl req -x509 -newkey rsa:2048 -keyout default.key -out default.pem -nodes -subj '/CN=localhost'
    warn: false
  args:
    chdir: /etc/nginx/ssl/
    creates: /etc/nginx/ssl/default.pem
