---
- name: Generate Private Key
  openssl_privatekey:
    path: /etc/nginx/ssl/default.key

- name: Generate Certificate Sign Request (CSR)
  openssl_csr:
    path: /etc/nginx/ssl/ansible.com.csr
    privatekey_path: /etc/nginx/ssl/default.key

- name: Generate self-signed SSL certificates
  openssl_certificate:
    path: /etc/nginx/ssl/default.pem
    privatekey_path: /etc/nginx/ssl/default.key
    csr_path: /etc/nginx/ssl/ansible.com.csr
    provider: selfsigned
