---
- name: Copy nginx UMI common configuration in place.
  template:
    src: umi_common.conf.j2
    dest: "{{ nginx_conf_files_path }}/site_include/umi_common.conf"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx

- name: Copy nginx UMI site configuration in place.
  template:
    src: umi_site.conf.j2
    dest: "{{ nginx_conf_files_path }}/site_avaliable/umi_site.conf"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx

- name: Copy nginx UMI site ssl configuration in place.
  template:
    src: umi_site_ssl.conf.j2
    dest: "{{ nginx_conf_files_path }}/site_avaliable/umi_site_ssl.conf"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx

- name: UMI enable default vhost setup.
  file:
    src: "{{ nginx_conf_files_path }}/site_avaliable/umi_site.conf"
    dest: "{{ nginx_conf_files_path }}/site_enabled/umi_site.conf"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
    state: link
  notify:
    - reload nginx

- name: UMI enable default ssl vhost setup.
  file:
    src: "{{ nginx_conf_files_path }}/site_avaliable/umi_site_ssl.conf"
    dest: "{{ nginx_conf_files_path }}/site_enabled/umi_site_ssl.conf"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
    state: link
  notify:
    - reload nginx
