---
# UMI common setup.
- name: Copy nginx configuration in place.
  template:
    src: umi_common.conf.j2
    dest: "{{ nginx_conf_file_path }}/site_include/umi_common.conf"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx

# UMI default vhost setup.
- name: Copy nginx configuration in place.
  template:
    src: umi_site.conf.j2
    dest: "{{ nginx_conf_file_path }}/site_avaliable/umi_site.conf"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx

# UMI default vhost setup.
- name: Copy nginx configuration in place.
  template:
    src: umi_site_ssl.conf.j2
    dest: "{{ nginx_conf_file_path }}/site_avaliable/umi_site_ssl.conf"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx

# UMI enable default vhost setup.
- name: Copy nginx configuration in place.
  template:
    src: "{{ nginx_conf_file_path }}/site_avaliable/umi_site.conf"
    dest: "{{ nginx_conf_file_path }}/site_enabled/umi_site.conf"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
    state: link
  notify:
    - reload nginx

# UMI enable default vhost setup.
- name: Copy nginx configuration in place.
  template:
    src: "{{ nginx_conf_file_path }}/site_avaliable/umi_site_ssl.conf"
    dest: "{{ nginx_conf_file_path }}/site_enabled/umi_site_ssl.conf"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
    state: link
  notify:
    - reload nginx