---
- name: Install dirmngr packages
  apt: pkg=dirmngr state=present

- name: install percona server apt-key
  apt_key:
    keyserver="{{ percona_mysql_key_server }}"
    id=9334A25F8507EFA5
    state=present

- name: Add Percona repositories
  apt:
      deb: "https://repo.percona.com/apt/percona-release_0.1-6.{{ansible_distribution_release}}_all.deb"
  register: percona_mysql_apt_repo

- name: update apt cache
  apt:
    update_cache=yes
  when: percona_mysql_apt_repo.changed
  tags: skip_ansible_lint

- name: install jemalloc package on debian family hosts
  apt:
    name=libjemalloc1
    state=present
  environment:
    DEBIAN_FRONTEND: noninteractive
  when: percona_mysql_include_tokudb_variables or percona_mysql_include_jemalloc_variables

- name: install numactl package on debian family hosts
  apt:
    name=numactl
    state=present
  environment:
    DEBIAN_FRONTEND: noninteractive
  when: percona_mysql_include_numa_variables

- name: install mysql package on debian family hosts
  apt:
    name="{{ percona_mysql_pkg }}"
    state={{ percona_mysql_state|default('present') }}
    #default_release="{{ percona_mysql_release }}"
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: percona_mysql_pkg_check_debian

#- name: create missing directory for Percona packaging
#  file:
#    path=/usr/lib64
#    state=directory
#- name: fix symlink issue in packaging
#  file:
#    src=/usr/lib/libgalera_smm.so
#    dest=/usr/lib64/libgalera_smm.so
#    owner=root
#    group=root
#    state=link

- name: install additional packages on debian family hosts
  apt:
    name={{ percona_mysql_additional_pkgs }}
    state=present
  environment:
    DEBIAN_FRONTEND: noninteractive
  tags: percona_mysql_additional_pkgs

- name: install mysql backup related packages on debian family hosts
  apt:
    name={{ percona_mysql_backup_pkgs }}
    state=present
  environment:
    DEBIAN_FRONTEND: noninteractive
  tags: percona_mysql_backup_pkgs

- name: install optional packages on debian family hosts
  apt:
    name={{ percona_mysql_optional_pkgs }}
    state=present
  environment:
    DEBIAN_FRONTEND: noninteractive
  tags: percona_mysql_optional_pkgs
