---
# playbook.yml file.
- hosts: install_python
  gather_facts: false
  become: true
  become_method: su
  pre_tasks:
   - name: Setup python
     raw: dnf install -y python3

- hosts: umi_fpm
  become: true
  become_method: su
  pre_tasks:
   - name: Set timezone to Europe/Moscow
     timezone:
      name: Europe/Moscow
  roles:
   - swap
   - pam-limits
   - systemd-overrides
   - locale
  # - sysctl
   - packages
   - timesync
   - percona_mysql
   - site_user
   - tmpfiles
   - role: repo-remi
     when: ansible_os_family == 'RedHat'
   - php
   - liquidprompt
   - nginx
   - nginx-umi-fpm
   - umi-cms
  tags: initial

#  tags:
#   - skip_ansible_lint


# register: _result
#  until: _result is succeeded

#- name: copy authorized keys
#  authorized_key:
#    user: "{{ item.0.username }}"
#    key: "{{ lookup('file', item.1) }}"
#  with_nested:
#    - "{{ users }}"
#    - "{{ lookup('fileglob', 'public_keys/*').split(',') }}"
