---
# playbook.yml file.
- hosts: install_python
  gather_facts: false
  become: true
  become_method: su
  pre_tasks:
   - name: Setup python
     raw: dnf install -y python3

- hosts: wordpress_httpd
  become: true
  become_method: su
  pre_tasks:
   - name: Set timezone to Europe/Moscow
     timezone:
      name: Europe/Moscow
  roles:
   - swap
   - pam-limits
   - systemd-overrides
   - locale
  # - sysctl
   - packages
   - timesync
   - percona_mysql
   - site_user
   - tmpfiles
   - role: repo-remi
     when: ansible_os_family == 'RedHat'
   - php
   - liquidprompt
   - nginx
   - httpd
   - nginx-wordpress-httpd
   - wordpress-cms
  tags: initial

# https://gist.github.com/ethanpil/1bfd01a817a8198369efec5c4cde6628
# https://codex.wordpress.org/Nginx
