---
- name: Download WordPress
  get_url:
   url: "https://ru.wordpress.org/wordpress-{{ wp_version }}-ru_RU.tar.gz"
   dest: "{{ site_root }}/wordpress-{{ wp_version }}.tar.gz"

- name: Extract archive
  unarchive:
    src: "{{ site_root }}/wordpress-{{ wp_version }}.tar.gz"
    dest: "{{ site_root }}"
    remote_src: yes

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/ warn=no
  register: "wp_salt"
  become: no
  tags:
  - skip_ansible_lint

- name: Copy WordPress config file
  template: src=wp-config.php dest={{ site_root }}
  run_once: true

- name: Change ownership of WordPress installation
  file: path={{ site_root }} owner={{ site_user }} group={{ site_user }} state=directory recurse=yes

- include: selinux.yml

- name: Delete mysql password
  file:
   path: /tmp/mysqlpasswordfile_user
   state: absent
