# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias mc='mc -x'

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

alias mytuner='/usr/local/bin/mysqltuner.pl'
alias myprimer='/usr/local/bin/tuning-primer.sh'
[[ $- = *i* ]] && source /opt/liquidprompt/liquidprompt

