---
# tasks file for mysql
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Configure MySQL
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
  notify:
    - Restart MySQL

- name: restart mysql
  service: name=mysql state=restarted enabled=yes

- name: Copy password into variable
  shell:  grep generated /var/log/mysqld.log | cut -c 92-
  register: mysql_password
  tags:
  - skip_ansible_lint

- name: Set new password from temporary password
  ignore_errors: yes
  shell: 'mysql -e "SET PASSWORD = PASSWORD(''{{ mysql_password.stdout }}'');" --connect-expired-password -uroot -p"{{ mysql_password.stdout }}"'
  tags:
  - skip_ansible_lint

- name: set password to file
  template:
    src: .my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root

