---
- name: Install MySQL repository
  yum: name={{ percona_yum_repo }} state=present

- name: Install Percona Server
  yum: name="Percona-Server-server-{{ percona_server_version }}" state=present
  register: percona_server

- name: Install Percona Utilities
  yum: 
    name: "{{ percona_utilities }}"
    state: present
