---
- name: repository | add public key
  apt_key:
    id: 9334A25F8507EFA5
    keyserver: keyserver.ubuntu.com
    state: present

- name: Add Percona repositories
  apt:
      deb: "https://repo.percona.com/apt/percona-release_0.1-6.{{ansible_distribution_release}}_all.deb"
  
#- name: Add Percona repositories
#  apt_repository:
#    repo: "{{ item }}"
#    state: present
#    update_cache: yes
#  with_items:
#     - deb http://repo.percona.com/apt {{ ansible_distribution_release }} main
#     - deb-src http://repo.percona.com/apt {{ ansible_distribution_release }} main

- name: Install python packages
  apt: pkg=python-mysqldb state=present

- name: Install Percona packages
  apt:
    pkg: "{{ percona_server }}"
    state: present
