---
- name: Copy UMI install file
  copy:
   src: install.php
   dest: "{{ site_root }}/install.php"

- name: Copy UMI index file
  copy:
   src: index.php
   dest: "{{ site_root }}/index.php"

- name: Copy UMI config file
  template: src=install.ini.j2 dest={{ site_root }}/install.ini

- name: Change ownership of UMI installation
  file: path="/home/{{ site_user }}" owner={{ site_user }} group={{ site_user }} state=directory recurse=yes

- name: Add UMI cron task
  cron:
   name: UMI cron task.
   user: "{{ site_user }}"
   job: "test -f {{ site_root }}/cron.php && { /usr/bin/php -f {{ site_root }}/cron.php; } >/dev/null 2>&1"

- name: Delete mysql password
  file:
   path: /tmp/mysqlpasswordfile_user
   state: absent
