---
- name: Add group "UMI"
  group:
   name: "{{ site_user }}"

- name: Add user "UMI"
  user:
   name: "{{ site_user }}"
   group: "{{ site_user }}"
   home: "/home/{{ site_user }}"

- name: Make UMI site dir
  file:
   path: "{{ site_root }}"
   state: directory

- name: Copy UMI install file
  copy:
   src: install.php
   dest: "{{ site_root }}/install.php"

- name: Copy UMI index file
  copy:
   src: index.php
   dest: "{{ site_root }}/index.php"

- name: Create UMI database
  mysql_db:
   name: "{{ umi_db_name }}"
   state: present

- name: Create UMI database user
  mysql_user:
   name: "{{ umi_db_user }}"
   password: "{{ umi_db_password }}"
   priv: "{{ umi_db_name }}.*:ALL"
   host: 'localhost'
   state: present

- name: Copy UMI config file
  template: src=install.ini.j2 dest={{ site_root }}/install.ini

- name: Change ownership of UMI installation
  file: path={{ site_root }} owner={{ site_user }} group={{ site_user }} state=directory recurse=yes

- name: Add UMI cron task
  cron:
   name: UMI cron task.
   user: "{{ site_user }}"
   job: "test -f {{ site_root }}/cron.php && { /usr/bin/php -f {{ site_root }}/cron.php; } >/dev/null 2>&1"

- name: Delete mysql password
  file:
   path: /tmp/mysqlpasswordfile_umi
   state: absent
