---
standart_packages:
 - bash-completion
 - bash-completion-extras
 - bind-utils
 - byobu
 - curl
 - deltarpm
 - git
 - htop
 - iftop
 - iotop
 - iperf
 - lsof
 - mc
 - nano
 - ncdu
 - net-tools
 - nmap
 #- policycoreutils-python
 - psmisc
 #- setools-console
 - traceroute
 - wget
 - yum-utils
