---
standart_packages:
 - bash-completion
 - dnsutils
 - curl
 - gdb
 - git
 - htop
 - iftop
 - iotop
 - iperf
 - lsof
 - mc
 - nano
 - ncdu
 - net-tools
 - nmap
 - psmisc
 - tmux
 - traceroute
 - wget
