---
- name: Add backports repo
  apt_repository:
    repo: "deb http://mirror.yandex.ru/debian {{ ansible_distribution_release }}-backports main contrib non-free"
    update_cache: yes
    
- name: Install Certbot.
  package: "name={{ certbot_package }} state=present"

- name: Set Certbot script variable.
  set_fact:
    certbot_script: "{{ certbot_package }}"
