---
- name: Add repo universe
  apt_repository:
    repo: "deb http://mirror.yandex.ru/ubuntu {{ ansible_distribution_release }} universe"
    update_cache: yes

- apt_repository:
    repo: ppa:certbot/certbot

- name: Install Certbot.
  package: "name={{ certbot_package }} state=present"

- name: Set Certbot script variable.
  set_fact:
    certbot_script: "{{ certbot_package }}"
