---
- import_tasks: include-vars.yml

- include_tasks: "{{ item }}"
  with_first_found:
    - "install-with-package-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "install-with-package-{{ ansible_distribution }}.yml"
    - "install-with-package-{{ ansible_os_family }}.yml"
    - "install-with-package.yml"

- name: generate cert
  command: "{{ certbot_script }} --agree-tos --register-unsafely-without-email --staple-ocsp --webroot certonly -w /opt/letsencrypt -d {{ server_hostname }} -d  www.{{ server_hostname }} creates=/etc/letsencrypt/live/{{ server_hostname }}/chain.pem"
  notify:
    - nginx reload
  ignore_errors: yes
  tags:
  - skip_ansible_lint

- import_tasks: renew-cron.yml
  when: certbot_auto_renew