---
- name: Attempting to execute os specific tasks (Debian)
  include_tasks: "sysctl_{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'Debian'

- name: Attempting to execute os specific tasks (RedHat)
  include_tasks: "sysctl_{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'RedHat'

# Setup/install tasks.
- name: Set distrib-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "defaults/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "defaults/{{ ansible_distribution }}.yml"
    - "defaults/{{ ansible_os_family }}.yml"

- name: Setup systemctl
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value.value }}"
    state: present
  loop: "{{ lookup('dict', sysctl) }}"

