---
- name: Ensure that the procps package is installed
  yum:
    name: procps
    state: present
  when: ansible_distribution_major_version <= '6'

- name: Ensure that the procps-ng package is installed
  yum:
    name: procps-ng
    state: present
  when: ansible_distribution_major_version >= '7'
