---
- name: Remove ntp packages
  apt:
   name: "{{ timesync_packages }}"
   state: absent
  register: timesync_packages_result
  until: timesync_packages_result is success

- name: Setup timesyncd
  service:
   name: systemd-timesyncd
   state: restarted
   enabled: true
