---
- name: Add repository for PHP versions (Ubuntu).
  apt_repository: repo='ppa:ondrej/php'
  when: ansible_distribution == "Ubuntu"

# Debian-specific tasks.
- name: Add dependencies for PHP versions (Debian).
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present
  when: ansible_distribution == "Debian"
  register: dependencies_for_php_result
  until: dependencies_for_php_result is succeeded

- name: Add Ondrej Sury's apt key (Debian).
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present
  when: ansible_distribution == "Debian"
  register: sury_apt_key_result
  until: sury_apt_key_result is succeeded

- name: Add Ondrej Sury's repo (Debian).
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state: present
  register: php_ondrej_debian_repo
  when: ansible_distribution == "Debian"

- name: alternatives php link updated
  alternatives:
    name: php
    path: "/usr/bin/php{{ php_default_version_debian }}"
  when: ansible_os_family == "Debian"
  ignore_errors: yes

- name: alternatives php-config link updated
  alternatives:
    name: php-config
    path: "/usr/bin/php-config{{ php_default_version_debian }}"
  when: ansible_os_family == "Debian"
  ignore_errors: yes

- name: alternatives phpdbg link updated
  alternatives:
    name: phpdbg
    path: "/usr/bin/phpdbg{{ php_default_version_debian }}"
  when: ansible_os_family == "Debian"
  ignore_errors: yes

- name: alternatives phpize link updated
  alternatives:
    name: phpize
    path: "/usr/bin/phpize{{ php_default_version_debian }}"
  when: ansible_os_family == "Debian"
  ignore_errors: yes

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  register: php_update_apt_cache
  until: php_update_apt_cache is succeeded

- name: Ensure PHP packages are installed.
  apt:
    name: "{{ php_packages }}"
    state: "{{ php_packages_state }}"
    install_recommends: "{{ php_install_recommends }}"
  register: php_package_install
  notify: restart webserver
  until: php_package_install is succeeded

- name: Delete APCu configuration file if this role will provide one.
  file:
    path: "{{ item }}/{{ php_apc_conf_filename }}"
    state: absent
  with_items: "{{ php_extension_conf_paths }}"
  when: php_enable_apc and php_package_install.changed
  notify: restart webserver
  tags:
   - skip_ansible_lint

- name: Delete OpCache configuration file if this role will provide one.
  file:
    path: "{{ item }}/{{ php_opcache_conf_filename }}"
    state: absent
  with_items: "{{ php_extension_conf_paths }}"
  when: php_opcache_enable and php_package_install.changed
  notify: restart webserver
  tags:
   - skip_ansible_lint
