---
- name: Ensure configuration path exist
  file:
    dest: "{{ systemd_overrides_config_file_path }}/{{ item }}.service.d/"
    state: directory
  loop: "{{ systemd_overrides_unit }}"

- name: Ensure configuration
  template:
    dest: "{{ systemd_overrides_config_file_path }}/{{ item }}.service.d/z_override.conf"
    src: z_override.conf.j2
  loop: "{{ systemd_overrides_unit }}"
  register: systemd_overrides_config_changed

- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes
  when: systemd_overrides_config_changed
