---
- name: Add site user group
  group:
   name: "{{ site_user }}"

- name: Add site user
  user:
   name: "{{ site_user }}"
   group: "{{ site_user }}"
   home: "/home/{{ site_user }}"
   shell: /bin/bash
   state: present

- name: Make site dir
  file:
   path: "{{ site_root }}"
   state: directory

- name: Create user database
  shell:
   cmd: mysql -e "SHOW DATABASES;" | grep {{ user_db_name }} || mysql -e "CREATE DATABASE {{ user_db_name }}\G"
   warn: false
# used command because of "Authentication plugin 'caching_sha2_password' cannot be loaded"
#  mysql_db:
#   name: "{{ user_db_name }}"
#   state: present

- name: Create user database user
  shell:
   cmd: mysql -e "SELECT User,Host FROM mysql.user;" | grep {{ user_db_user }} || mysql -e "CREATE USER '{{ user_db_user }}'@'localhost' IDENTIFIED BY '{{ user_db_password }}';"
   warn: false
#  mysql_user:
#   name: "{{ user_db_user }}"
#   password: "{{ user_db_password }}"
#   priv: "{{ user_db_name }}.*:ALL"
#   host: 'localhost'
#   state: present

- name: Set permissions for user on database
  command:
   cmd: mysql -e "GRANT ALL PRIVILEGES ON {{ user_db_name }}.* TO '{{ user_db_user }}'@'localhost';"
   warn: false

- name: Copy DB config file
  template: src=install.ini.j2 dest={{ site_root }}/install.ini force=false

- name: Change ownership of site installation
  file: path="/home/{{ site_user }}" owner={{ site_user }} group={{ site_user }} state=directory recurse=yes
