---
- name: Add site user group
  group:
   name: "{{ site_user }}"

- name: Add site user
  user:
   name: "{{ site_user }}"
   group: "{{ site_user }}"
   home: "/home/{{ site_user }}"

- name: Make site dir
  file:
   path: "{{ site_root }}"
   state: directory

- name: Create user database
  mysql_db:
   name: "{{ user_db_name }}"
   state: present

- name: Create user database user
  mysql_user:
   name: "{{ user_db_user }}"
   password: "{{ user_db_password }}"
   priv: "{{ user_db_name }}.*:ALL"
   host: 'localhost'
   state: present

- name: Copy DB config file
  template: src=install.ini.j2 dest={{ site_root }}/install.ini

- name: Change ownership of site installation
  file: path="/home/{{ site_user }}" owner={{ site_user }} group={{ site_user }} state=directory recurse=yes
